Add integration test for multi-shot server
Passes on macOS without code changes.

Fails on Linux with:

thread 'main' panicked at src/bin/spawn_client_test_helper.rs:25:71:
connect failed: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/result.rs:1700:5
   3: core::result::Result<T,E>::expect
             at /home/glyn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1061:23
   4: spawn_client_test_helper::main
             at ./src/bin/spawn_client_test_helper.rs:25:33
   5: core::ops::function::FnOnce::call_once
             at /home/glyn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test spawn_multi_shot_server_clients ... FAILED

failures:

---- spawn_multi_shot_server_clients stdout ----
thread 'spawn_multi_shot_server_clients' panicked at tests/integration_test.rs:67:5:
child process failed with exit status code 101
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: integration_test::await_child_process
             at ./tests/integration_test.rs:67:5
   3: integration_test::spawn_multi_shot_server_clients
             at ./tests/integration_test.rs:48:5
   4: integration_test::spawn_multi_shot_server_clients::{{closure}}
             at ./tests/integration_test.rs:37:37
   5: core::ops::function::FnOnce::call_once
             at /home/glyn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.